apiVersion: v1
kind: Pod
metadata:
  name: payments-default-limits
  namespace: payments
spec:
  securityContext:
    runAsNonRoot: true
  containers:
  - name: api
    image: ghcr.io/minhkhoa2209/w10-api@sha256:616ae00b4ad60d69be24ba476e1ab87d6f2c7b9a3195caa90dccaa7ef1c46705
    command: ["sh", "-c", "sleep 3600"]
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
      allowPrivilegeEscalation: false
---
apiVersion: v1
kind: Pod
metadata:
  name: payments-over-quota
  namespace: payments
spec:
  securityContext:
    runAsNonRoot: true
  containers:
  - name: api
    image: ghcr.io/minhkhoa2209/w10-api@sha256:616ae00b4ad60d69be24ba476e1ab87d6f2c7b9a3195caa90dccaa7ef1c46705
    command: ["sh", "-c", "sleep 3600"]
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
      allowPrivilegeEscalation: false
    resources:
      requests:
        cpu: "2"
        memory: 3Gi
      limits:
        cpu: "3"
        memory: 3Gi
