apiVersion: policy.sigstore.dev/v1beta1
kind: ClusterImagePolicy
metadata:
  name: require-w10-api-signature
spec:
  images:
  - glob: ghcr.io/minhkhoa2209/w10-api:*
  - glob: ghcr.io/minhkhoa2209/w10-api@sha256:*
  authorities:
  - name: authority-0
    key:
      data: |
        -----BEGIN PUBLIC KEY-----
        MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEpbUc4utuuZnehachYUISxX8RlwiL
        p4deYrP+lwl0Jru4E7cGyWEjaUtmUijIl6XPbbMQlPiXebW8bK5fhkNyCw==
        -----END PUBLIC KEY-----
  mode: enforce
